# Generated by Django 5.0.1 on 2024-02-07 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UsersInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('skills', models.TextField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phonenumber', models.IntegerField(null=True, unique=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('facebookLink', models.URLField(blank=True, null=True)),
                ('instagramLink', models.URLField(blank=True, null=True)),
                ('linkedinLink', models.URLField(blank=True, null=True)),
                ('githubLink', models.URLField(blank=True, null=True)),
                ('behanceLink', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField(null=True)),
                ('image', models.ImageField(upload_to='product_images/')),
                ('websiteurl', models.URLField(blank=True, null=True)),
                ('added_time', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
            ],
        ),
    ]
